# Define your default values here
# You can override these values when installing the chart

# Default values for ilc-app-chart.
nameOverride: ""
env: "production"  # Environment name
image:
  repository: your/image-repo
  tag: latest

service:
  port: 8080

ingress:
  enabled: true
  host: ilc-app.example.com
  paths:
    - /

# Environment variables and Java options in ConfigMap
envConfigMap:
  ENV_VAR_1: value1
  ENV_VAR_2: value2
  JAVA_OPTS: "-Xmx512m -Xms256m"

# Path to application properties file
applicationPropertiesPath: /path/to/application.properties

# Example of secrets
secrets:
  db-credentials:
    username: admin
    password: adminpassword
