# Define your default values here
# You can override these values when installing the chart

# Image details
image:
  repository: your/image-repo
  tag: latest
  pullPolicy: IfNotPresent

# Service details
service:
  name: ilc-app
  type: ClusterIP
  port: 8080

# Ingress details
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ilc-app.example.com
      paths:
        - /

# Environment variables
env:
  - name: ENV_VAR_1
    value: value1
  - name: ENV_VAR_2
    value: value2
  # Add more environment variables as needed
