# Define your default values here
# You can override these values when installing the chart

# Default values for ilc-app-chart.
nameOverride: ""
env: ""
image:
  repository: your/image-repo
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: true
  host: ilc-app.example.com
  paths:
    - /

envConfigMap: {}

applicationPropertiesPath: /path/to/application.properties

secrets: []
