apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-{{ .Values.env }}-secrets
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
