apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-{{ .Values.env }}-service
spec:
  selector:
    app: {{ .Values.name }}-{{ .Values.env }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
